export const TYPES = {
  APP: {
    CHANGE_TEXT: 'APP/CHANGE_TEXT',
  },
  TABLE: {
    APPLY_STYLE: 'APPLY_STYLE',
    RESIZE: 'TABLE/RESIZE',
    CHANGE_STYLES: 'TABLE/CHANGE_STYLES',
  },
  HEADER: {
    CHANGE_TITLE: 'HEADER/CHANGE_TITLE',
  },
}
